workflows:
  android-build:
    name: Build Android - مين فينا؟
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      java: 17
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get packages
        script: flutter pub get
      - name: Build App Bundle
        script: flutter build appbundle --debug
    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab