name: meen_fena
description: "مين فينا؟ - لعبة استنتاج اجتماعي مصرية"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  provider: ^6.1.1
  shared_preferences: ^2.3.4
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  uuid: ^4.2.1
  collection: ^1.18.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true