org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# ⚠️ هام: تعطيل DSL الجديد تماماً
android.newDsl=false
android.disableResourceValidation=true

flutter.minSdkVersion=21
flutter.targetSdkVersion=34
flutter.compileSdkVersion=34
flutter.ndkVersion=27.0.12077973

kotlin.code.style=official

android.enableR8.fullMode=true