org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# ⚠️ هام جداً: تعطيل واجهة AGP الجديدة
android.newDsl=false
systemProp.android.newDsl=false

flutter.minSdkVersion=21
flutter.targetSdkVersion=35
flutter.compileSdkVersion=35

kotlin.code.style=official
android.enableR8.fullMode=true